app:
  name: "werite"
  version: 1 # 0=debug 1=release
  zoneoffset: 8 # 时区偏移量，东8
  static: "static"
  cacheDir: "./cache/"
httpserver:
  addr: ":8888"
log:
  dir: "./log/"
db:
  type: "sqlite"
  # dsn: "devel:i18n@tcp(127.0.0.1:3306)/werite_db?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  dsn: "./werite.db"
  active: 32
  idle: 30
  idletimeout: 14400
  debug: true
redis:
  # 发布消息 的redis地址
  addr: "127.0.0.1:6379"
  password: "i18n!@#"
  db: 0
