// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBlogger = "blogger"

// Blogger mapped from table <blogger>
type Blogger struct {
	BlogName    string `gorm:"column:blog_name;not null" json:"blog_name"`
	SubTitle    string `gorm:"column:sub_title;not null" json:"sub_title"`
	BeiAn       string `gorm:"column:bei_an;not null" json:"bei_an"`
	BTitle      string `gorm:"column:b_title;not null" json:"b_title"`
	Copyright   string `gorm:"column:copyright;not null" json:"copyright"`
	SeriesSay   string `gorm:"column:series_say;not null" json:"series_say"`
	ArchivesSay string `gorm:"column:archives_say;not null" json:"archives_say"`
}

// TableName Blogger's table name
func (*Blogger) TableName() string {
	return TableNameBlogger
}
