// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID        int32          `gorm:"column:id;primaryKey" json:"id"`
	UserID    int32          `gorm:"column:user_id;not null" json:"user_id"`
	Author    string         `gorm:"column:author;not null" json:"author"`
	Text      string         `gorm:"column:text;not null" json:"text"`
	Email     string         `gorm:"column:email;not null" json:"email"`
	IP        string         `gorm:"column:ip;not null" json:"ip"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;not null" json:"deleted_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:current_timestamp" json:"updated_at"`
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:current_timestamp" json:"created_at"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
